
'use strict';

goog.provide('Blockly.ScratchMsgs.allLocales');

goog.require('Blockly.ScratchMsgs');

Blockly.ScratchMsgs.locales["ja"] =
{
    // Elements
    "CATEGORY_MAIN": "お題のブロック",
    //basic
    "CATEGORY_BASIC": "基本",
    "DOCTYPEHTML": "<!DOCTYPE html>",
    "ELEMENT_HTML_TOP": "<html %1 > %2 %4 %3",
    "ELEMENT_HTML_BOTTOM": "</html>",
    "ELEMENT_HEAD_TOP": "<head> %1 %2",
    "ELEMENT_HEAD_BOTTOM": "</head>",
    "ELEMENT_BODY_TOP": "<body %1 %2 > %3 %4",
    "ELEMENT_BODY_BOTTOM": "</body>",
    //meta
    "CATEGORY_META": "情報",
    "ELEMENT_BASE": "<base %1>",
    "ELEMENT_LINK": "<link %1>",
    "ELEMENT_META": "<meta %1>",
    "ELEMENT_STYLE_TOP": "<style> %1 %2",
    "ELEMENT_STYLE_BOTTOM": "</style>",
    "ELEMENT_TITLE_TOP": "<title> %1 %2",
    "ELEMENT_TITLE_BOTTOM": "</title>",
    //structure
    "CATEGORY_STRUCTURE": "構成",
    "ELEMENT_H1_TOP": "<h1 %1 %2 > %3 %4",
    "ELEMENT_H1_BOTTOM": "</h1>",
    "ELEMENT_H2_TOP": "<h2 %1 %2 > %3 %4",
    "ELEMENT_H2_BOTTOM": "</h2>",
    "ELEMENT_H3_TOP": "<h3 %1 %2 > %3 %4",
    "ELEMENT_H3_BOTTOM": "</h3>",
    "ELEMENT_BLOCKQUOTE_TOP": "<blockquote %1 %2 > %3 %4",
    "ELEMENT_BLOCKQUOTE_BOTTOM": "</blockquote>",
    "ELEMENT_DIV_TOP": "<div %1 %2 > %3 %4",
    "ELEMENT_DIV_BOTTOM": "</div>",
    "ELEMENT_HR": "<hr %1>",
    "ELEMENT_LI_TOP": "<li %1 %2 > %3 %4",
    "ELEMENT_LI_BOTTOM": "</li>",
    "ELEMENT_OL_TOP": "<ol %1 %2 > %3 %4",
    "ELEMENT_OL_BOTTOM": "</ol>",
    "ELEMENT_P_TOP": "<p %1 %2 > %3 %4",
    "ELEMENT_P_BOTTOM": "</p>",
    "ELEMENT_UL_TOP": "<ul %1 %2 > %3 %4",
    "ELEMENT_UL_BOTTOM": "</ul>",
    //modifier
    "CATEGORY_MODIFIER": "修飾",
    "ELEMENT_A_TOP": "<a %1 %2 > %3 %4",
    "ELEMENT_A_BOTTOM": "</a>",
    "ELEMENT_B_TOP": "<b> %1 %2",
    "ELEMENT_B_BOTTOM": "</b>",
    "ELEMENT_BR": "<br>",
    "ELEMENT_CODE_TOP": "<code> %1 %2",
    "ELEMENT_CODE_BOTTOM": "</code>",
    "ELEMENT_EM_TOP": "<em> %1 %2",
    "ELEMENT_EM_BOTTOM": "</em>",
    "ELEMENT_I_TOP": "<i> %1 %2",
    "ELEMENT_I_BOTTOM": "</i>",
    "ELEMENT_MARK_TOP": "<mark> %1 %2",
    "ELEMENT_MARK_BOTTOM": "</mark>",
    "ELEMENT_Q_TOP": "<q> %1 %2",
    "ELEMENT_Q_BOTTOM": "</q>",
    "ELEMENT_RP_TOP": "<rp> %1 %2",
    "ELEMENT_RP_BOTTOM": "</rp>",
    "ELEMENT_RT_TOP": "<rt> %1 %2",
    "ELEMENT_RT_BOTTOM": "</rt>",
    "ELEMENT_RUBY_TOP": "<ruby> %1 %2",
    "ELEMENT_RUBY_BOTTOM": "</ruby>",
    "ELEMENT_S_TOP": "<s> %1 %2",
    "ELEMENT_S_BOTTOM": "</s>",
    "ELEMENT_SMALL_TOP": "<small> %1 %2",
    "ELEMENT_SMALL_BOTTOM": "</small>",
    "ELEMENT_SPAN_TOP": "<span %1 %2 > %3 %4",
    "ELEMENT_SPAN_BOTTOM": "</span>",
    "ELEMENT_STRONG_TOP": "<strong> %1 %2",
    "ELEMENT_STRONG_BOTTOM": "</strong>",
    "ELEMENT_SUB_TOP": "<sub> %1 %2",
    "ELEMENT_SUB_BOTTOM": "</sub>",
    "ELEMENT_SUP_TOP": "<sup> %1 %2",
    "ELEMENT_SUP_BOTTOM": "</sup>",
    "ELEMENT_U_TOP": "<u> %1 %2",
    "ELEMENT_U_BOTTOM": "</u>",
    //embed
    "CATEGORY_EMBED": "埋め込み",
    "ELEMENT_AREA": "<area %1>",
    "ELEMENT_AUDIO_TOP": "<audio %1 %2 > %3 %4",
    "ELEMENT_AUDIO_BOTTOM": "</audio>",
    "ELEMENT_IMG": "<img %1>",
    "ELEMENT_MAP_TOP": "<map %1 %2 > %3 %4",
    "ELEMENT_MAP_BOTTOM": "</map>",
    "ELEMENT_TRACK": "<track %1>",
    "ELEMENT_VIDEO_TOP": "<video %1 %2 > %3 %4",
    "ELEMENT_VIDEO_BOTTOM": "</video>",
    "ELEMENT_EMBED": "<embed %1>",
    "ELEMENT_IFRAME_TOP": "<iframe %1 %2 > %3 %4",
    "ELEMENT_IFRAME_BOTTOM": "</iframe>",
    "ELEMENT_OBJECT_TOP": "<object %1 %2 > %3 %4",
    "ELEMENT_OBJECT_BOTTOM": "</object>",
    "ELEMENT_SOURCE": "<source %1>",
    //table
    "CATEGORY_TABLE": "表",
    "ELEMENT_CAPTION_TOP": "<caption %1 %2 > %3 %4",
    "ELEMENT_CAPTION_BOTTOM": "</caption>",
    "ELEMENT_COL": "<col %1>",
    "ELEMENT_COLGROUP_TOP": "<colgroup %1 %2 > %3 %4",
    "ELEMENT_COLGROUP_BOTTOM": "</colgroup>",
    "ELEMENT_TABLE_TOP": "<table %1 %2 > %3 %4",
    "ELEMENT_TABLE_BOTTOM": "</table>",
    "ELEMENT_TBODY_TOP": "<tbody %1 %2 > %3 %4",
    "ELEMENT_TBODY_BOTTOM": "</tbody>",
    "ELEMENT_TD_TOP": "<td %1 %2 > %3 %4",
    "ELEMENT_TD_BOTTOM": "</td>",
    "ELEMENT_TFOOT_TOP": "<tfoot %1 %2 > %3 %4",
    "ELEMENT_TFOOT_BOTTOM": "</tfoot>",
    "ELEMENT_TH_TOP": "<th %1 %2 > %3 %4",
    "ELEMENT_TH_BOTTOM": "</th>",
    "ELEMENT_THEAD_TOP": "<thead %1 %2 > %3 %4",
    "ELEMENT_THEAD_BOTTOM": "</thead>",
    "ELEMENT_TR_TOP": "<tr %1 %2 > %3 %4",
    "ELEMENT_TR_BOTTOM": "</tr>",
    //form
    "CATEGORY_FORM": "フォーム",
    "ELEMENT_BUTTON_TOP": "<button %1 %2 > %3 %4",
    "ELEMENT_BUTTON_BOTTOM": "</button>",
    "ELEMENT_DATALIST_TOP": "<datalist %1 %2 > %3 %4",
    "ELEMENT_DATALIST_BOTTOM": "</datalist>",
    "ELEMENT_FORM_TOP": "<form %1 %2 > %3 %4",
    "ELEMENT_FORM_BOTTOM": "</form>",
    "ELEMENT_INPUT": "<input %1>",
    "ELEMENT_LABEL_TOP": "<label %1 %2 > %3 %4",
    "ELEMENT_LABEL_BOTTOM": "</label>",
    "ELEMENT_METER_TOP": "<meter %1 %2 > %3 %4",
    "ELEMENT_METER_BOTTOM": "</meter>",
    "ELEMENT_OPTGROUP_TOP": "<optgroup %1 %2 > %3 %4",
    "ELEMENT_OPTGROUP_BOTTOM": "</optgroup>",
    "ELEMENT_OPTION_TOP": "<option %1 %2 > %3 %4",
    "ELEMENT_OPTION_BOTTOM": "</option>",
    "ELEMENT_OUTPUT_TOP": "<output %1 %2 > %3 %4",
    "ELEMENT_OUTPUT_BOTTOM": "</output>",
    "ELEMENT_PROGRESS_TOP": "<progress %1 %2 > %3 %4",
    "ELEMENT_PROGRESS_BOTTOM": "</progress>",
    "ELEMENT_SELECT_TOP": "<select %1 %2 > %3 %4",
    "ELEMENT_SELECT_BOTTOM": "</select>",
    "ELEMENT_TEXTAREA_TOP": "<textarea %1 %2 > %3 %4",
    "ELEMENT_TEXTAREA_BOTTOM": "</textarea>",
    //others
    "CATEGORY_OTHERS": "その他の要素",
    "ELEMENT_DEL_TOP": "<del %1 %2 > %3 %4",
    "ELEMENT_DEL_BOTTOM": "</del>",
    "ELEMENT_INS_TOP": "<ins %1 %2 > %3 %4",
    "ELEMENT_INS_BOTTOM": "</ins>",
    "ELEMENT_DETAILS_TOP": "<details %1 %2 > %3 %4",
    "ELEMENT_DETAILS_BOTTOM": "</details>",
    "ELEMENT_DIALOG_TOP": "<dialog %1 %2 > %3 %4",
    "ELEMENT_DIALOG_BOTTOM": "</dialog>",
    "ELEMENT_SUMMARY_TOP": "<summary %1 %2 > %3 %4",
    "ELEMENT_SUMMARY_BOTTOM": "</summary>",
    "ELEMENT_PARAM": "<param %1>",
    "ELEMENT_WBR": "<wbr %1>",
    // text
    "ELEMENT_WEBEDITOR-TEXT": "%1",

    // Attributes
    "CATEGORY_ATTRIBUTES": "属性",
    "ATTRIBUTE_ACCEPT": "accept=\" %1 \"",
    "ATTRIBUTE_ACCESSKEY": "accesskey=\" %1 \"",
    "ATTRIBUTE_ALLOW": "allow=\" %1 \"",
    "ATTRIBUTE_ALT": "alt=\" %1 \"",
    "ATTRIBUTE_AUTOCAPITALIZE": "autocapitalize=\" %1 \"",
    "ATTRIBUTE_AUTOCOMPLETE": "autocomplete=\" %1 \"",
    "ATTRIBUTE_AUTOFOCUS": "autofocus=\" %1 \"",
    "ATTRIBUTE_AUTOPLAY": "autoplay=\" %1 \"",
    "ATTRIBUTE_CAPTURE": "capture=\" %1 \"",
    "ATTRIBUTE_CHARSET": "charset=\" %1 \"",
    "ATTRIBUTE_CHECKED": "checked=\" %1 \"",
    "ATTRIBUTE_CLASS": "class=\" %1 \"",
    "ATTRIBUTE_COLS": "cols=\" %1 \"",
    "ATTRIBUTE_COLSPAN": "colspan=\" %1 \"",
    "ATTRIBUTE_CONTENTEDITABLE": "contenteditable=\" %1 \"",
    "ATTRIBUTE_CONTROLS": "controls=\" %1 \"",
    "ATTRIBUTE_COORDS": "coords=\" %1 \"",
    "ATTRIBUTE_DATA": "data=\" %1 \"",
    "ATTRIBUTE_DEFAULT": "default=\" %1 \"",
    "ATTRIBUTE_DIR": "dir=\" %1 \"",
    "ATTRIBUTE_DISABLED": "disabled=\" %1 \"",
    "ATTRIBUTE_DOWNLOAD": "download=\" %1 \"",
    "ATTRIBUTE_FOR": "for=\" %1 \"",
    "ATTRIBUTE_HEADERS": "headers=\" %1 \"",
    "ATTRIBUTE_HIGH": "high=\" %1 \"",
    "ATTRIBUTE_HEIGHT": "height=\" %1 \"",
    "ATTRIBUTE_HREF": "href=\" %1 \"",
    "ATTRIBUTE_ID": "id=\" %1 \"",
    "ATTRIBUTE_KIND": "kind=\" %1 \"",
    "ATTRIBUTE_LABEL": "label=\" %1 \"",
    "ATTRIBUTE_LANG": "lang=\" %1 \"",
    "ATTRIBUTE_LIST": "list=\" %1 \"",
    "ATTRIBUTE_LOOP": "loop=\" %1 \"",
    "ATTRIBUTE_LOW": "low=\" %1 \"",
    "ATTRIBUTE_MAX": "max=\" %1 \"",
    "ATTRIBUTE_MAXLENGTH": "maxlength=\" %1 \"",
    "ATTRIBUTE_MIN": "min=\" %1 \"",
    "ATTRIBUTE_MINLENGTH": "minlength=\" %1 \"",
    "ATTRIBUTE_MULTIPLE": "multiple=\" %1 \"",
    "ATTRIBUTE_MUTED": "muted=\" %1 \"",
    "ATTRIBUTE_NAME": "name=\" %1 \"",
    "ATTRIBUTE_OPEN": "open=\" %1 \"",
    "ATTRIBUTE_OPTIMUM": "optimum=\" %1 \"",
    "ATTRIBUTE_PATTERN": "pattern=\" %1 \"",
    "ATTRIBUTE_PLACEHOLDER": "placeholder=\" %1 \"",
    "ATTRIBUTE_POSTER": "poster=\" %1 \"",
    "ATTRIBUTE_READONLY": "readonly=\" %1 \"",
    "ATTRIBUTE_REL": "rel=\" %1 \"",
    "ATTRIBUTE_REQUIRED": "required=\" %1 \"",
    "ATTRIBUTE_ROWS": "rows=\" %1 \"",
    "ATTRIBUTE_ROWSPAN": "rowspan=\" %1 \"",
    "ATTRIBUTE_SANDBOX": "sandbox=\" %1 \"",
    "ATTRIBUTE_SCOPE": "scope=\" %1 \"",
    "ATTRIBUTE_SHAPE": "shape=\" %1 \"",
    "ATTRIBUTE_SIZE": "size=\" %1 \"",
    "ATTRIBUTE_SPAN": "span=\" %1 \"",
    "ATTRIBUTE_SRC": "src=\" %1 \"",
    "ATTRIBUTE_SRCLANG": "srclang=\" %1 \"",
    "ATTRIBUTE_STEP": "step=\" %1 \"",
    "ATTRIBUTE_STYLE": "style=\" %1 \"",
    "ATTRIBUTE_TARGET": "target=\" %1 \"",
    "ATTRIBUTE_TITLE": "title=\" %1 \"",
    "ATTRIBUTE_TYPE": "type=\" %1 \"",
    "ATTRIBUTE_USEMAP": "usemap=\" %1 \"",
    "ATTRIBUTE_VALUE": "value=\" %1 \"",
    "ATTRIBUTE_WIDTH": "width=\" %1 \"",
    // join
    "ATTRIBUTES_JOIN": "%1 %2",


    "DUPLICATE": "複製",
    "DELETE": "削除",
    "ADD_COMMENT": "コメントを追加",
    "REMOVE_COMMENT": "コメントを削除",
    "DELETE_BLOCK": "ブロックを削除",
    "DELETE_X_BLOCKS": "%1 個のブロックを削除",
    "DELETE_ALL_BLOCKS": "%1 個のブロックをすべて削除しますか?",
    "CLEAN_UP": "きれいにする",
    "HELP": "ヘルプ",
    "UNDO": "取り消し",
    "REDO": "やり直し",
    "EDIT_PROCEDURE": "編集",
    "SHOW_PROCEDURE_DEFINITION": "定義へ行く",
    "WORKSPACE_COMMENT_DEFAULT_TEXT": "コメントを書く...",
    "COLOUR_HUE_LABEL": "色",
    "COLOUR_SATURATION_LABEL": "鮮やかさ",
    "COLOUR_BRIGHTNESS_LABEL": "明るさ",
    "CHANGE_VALUE_TITLE": "値を変える:"
};